on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: pmmyregistry.azurecr.io
        username: ${{ secrets.acr_pmmyregistry_username }}
        password: ${{ secrets.acr_pmmyregistry_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t pmmyregistry.azurecr.io/pmtestakscluster:${{ github.sha }}
        docker push pmmyregistry.azurecr.io/pmtestakscluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_pmtestakscluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep pmtestaksclusterdee9 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace pmtestaksclusterdee9`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: pmtestaksclusterdee9
        container-registry-url: pmmyregistry.azurecr.io
        container-registry-username: ${{ secrets.acr_pmmyregistry_username }}
        container-registry-password: ${{ secrets.acr_pmmyregistry_password }}
        secret-name: pmtestakscludockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: pmtestaksclusterdee9
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
        images: |
          pmmyregistry.azurecr.io/pmtestakscluster:${{ github.sha }}
        imagepullsecrets: |
          pmtestakscludockerauth